CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS articles (
    id VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    comment TEXT NOT NULL,
    article TEXT NOT NULL,
    user_id VARCHAR(255) NOT NULL REFERENCES users (id),
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted TIMESTAMP WITH TIME ZONE
);